### ISSUE TITLE
Search text persists between fields

### ISSUE THREAD

**Issue by muckypuddle-nick** [mdixon18/fontawesome#8]
Hi,

If you have a couple of fields and use the search field in one of them, the searching persists between all of them. This is not reflected by showing the text that is searched.

 Video of the issue: http://support-media.muckypuddle.me/d87147545c05

**Comment by httpware** [comment]
This has been updated and will be deployed in the next couple of days.

Apologies for the delay, this wasn't maintained but will be going forward.
